define([], function(){
    return {
            users:{
                    login:{
                        url:'http://187.188.96.133:8082/ServiceBosque/Login',
                        //url:'data/loging.json',
                        type:'POST',
                        dataType:'json'//,
                        //contentType:'application/json'
                    },
                    logout:{
                        url:'http://187.188.96.133:8082/siap/logout',
                        type:'GET',
                        dataType:'json',
                        contentType:'application/json'
                    },
                    add:{
                        url:'http://187.188.96.133:8082/ServiceBosque/User?action=set',
                        type:'POST',
                        dataType:'json'
                    },
                    edit:{
                        url:'http://187.188.96.133:8082/ServiceBosque/User?action=edit',
                        type:'POST',
                        dataType:'json'
                    },
                    del:{
                        url:'http://187.188.96.133:8082/ServiceBosque/User?action=delete',
                        type:'GET',
                        dataType:'json'
                    },
                    search:{
                        url:'http://187.188.96.133:8082/ServiceBosque/User?',
                        type:'POST',
                        dataType:'json'
                    }
            },
            tabular:{
                    add:{
                        url:'http://187.188.96.133:8082/ServiceBosque/Table?',
                        type:'POST',
                        dataType:'json'
                    },
                    edit:{
                        url:'http://187.188.96.133:8082/ServiceBosque/Table?',
                        type:'POST',
                        dataType:'json'
                    },
                    del:{
                        url:'http://187.188.96.133:8082/ServiceBosque/Table?action=delete',
                        type:'GET',
                        dataType:'json'
                    },
                    search:{
                        url:'http://187.188.96.133:8082/ServiceBosque/Table?',
                        type:'POST',
                        dataType:'json'
                    },
                    get:{
                        url:'http://187.188.96.133:8082/ServiceBosque/Table?',
                        type:'GET',
                        dataType:'json'
                    },
                    getFields:{
                        url:'http://187.188.96.133:8082/ServiceBosque/Table?',
                                type:'POST',
                                dataType:'json'
                    },
                    getFolio:{
                        url:'http://187.188.96.133:8082/ServiceBosque/Folio?',
                                type:'POST',
                                dataType:'json'
                    },
//   Servivio para la consulta del numero de incendio consecutivo por año para el programa de incendios 
//        Mike Omar Martínez 16/06/2016
                     getNumIncendio:{
                        url:'http://187.188.96.133:8082/ServiceBosque/NumIncendio?',
                                type:'POST',
                                dataType:'json'
                    }
             // fin codigo mike        
            },
	    
            multirecords:{
                    getInputs:{
                        url:'http://187.188.96.133:8082/ServiceBosque/Subtable?',
                        type:'GET',
                        dataType:'json'
                    },
                    getList:{
                         url:'http://187.188.96.133:8082/ServiceBosque/Subtable?',
                        type:'GET',
                        dataType:'json'
                    },
                    deleteTemporal:{
                        url:'http://187.188.96.133:8082/ServiceBosque/Table?',
                        type:'GET',
                        dataType:'json'
                    },
                    add:{
                        url:'http://187.188.96.133:8082/ServiceBosque/Subtable?',
                        type:'POST',
                        dataType:'json'
                    },
                    edit:{
                        url:'http://187.188.96.133:8082/ServiceBosque/Subtable?',
                        type:'POST',
                        dataType:'json'
                    },
                    del:{
                        url:'http://187.188.96.133:8082/ServiceBosque/Subtable?action=delete',
                        type:'GET',
                        dataType:'json'
                    },
                    get:{
                        url:'http://187.188.96.133:8082/ServiceBosque/Subtable?action=delete',
                        type:'GET',
                        dataType:'json'
                    },
                    getVolumen:{
                        url:'http://187.188.96.133:8082/ServiceBosque/Subtable?',
                        type:'GET',
                        dataType:'json'
                    },
                    getAnioAreaCorta:{
                        url:'http://187.188.96.133:8082/ServiceBosque/Subtable?',
                        type:'GET',
                        dataType:'json'
                    }
            },
            reports:{
                    getFields:{
                        url:'http://187.188.96.133:8082/ServiceBosque/Table?',
                        type:'POST',
                        dataType:'json'
                    },
                    getReport:{
                        url:'http://187.188.96.133:8082/ServiceBosque/Report?',
                        type:'POST',
                        dataType:'json'
                    },
                    getGraph:{
                        url:'http://187.188.96.133:8082/ServiceBosque/Graph?',
                        type:'POST',
                        dataType:'json'
                    }
            },
            workTeams:{
                    
                    getNodes:{
                        url:'http://187.188.96.133:8082/siap/users/dependants',
                        type:'GET',
                        dataType:'json',
                        contentType:'application/json'
                        
                    },
                    actions:{
                        url:'http://187.188.96.133:8082/Service/Users?',
                        type:'GET',
                        dataType:'json',
                        contentType:'application/json'
                    }
            },
            actions:{
                set:{
                        url:'http://187.188.96.133:8082/Service/Actions?',
                        type:'GET',
                        dataType:'json',
                        contentType:'application/json'
                    },
                get:{
                        url:'http://187.188.96.133:8082/Service/Actions?',
                        type:'GET',
                        dataType:'json',
                        contentType:'application/json'
                    }
                
            },
            assignCharge:{
                getList:{
                        url:'http://187.188.96.133:8082/Service/AssignCharge?',
                        type:'GET',
                        dataType:'json',
                        contentType:'application/json'
                },
                setList:{
                        
                        url:'http://187.188.96.133:8082/Service/AssignCharge?',
                        type:'POST',
                        dataType:'json',
                        contentType:'application/json'
                }
            },
            deliveredCharge:{
                getByDelivering:{
                        url:'http://187.188.96.133:8082/Service/AssignCharge?',
                        type:'GET',
                        dataType:'json',
                        contentType:'application/json'
                },
                getDelivered:{
                        url:'http://187.188.96.133:8082/Service/AssignCharge?',
                        type:'GET',
                        dataType:'json',
                        contentType:'application/json'
                }
            },
            validateCharge:{
                get:{
                        url:'http://187.188.96.133:8082/Service/ValidateCharge?',
                        type:'GET',
                        dataType:'json',
                        contentType:'application/json'
                },
                set:{
                        url:'http://187.188.96.133:8082/Service/ValidateCharge?',
                        type:'POST',
                        dataType:'json',
                        contentType:'application/json'
                }
            },
            requestField:{
                    data:{
                            url:'http://187.188.96.133:8082/ServiceBosque/',
                            type:'POST',
                            dataType:'json'
                    }
            },
            image:{
                    upload:{
                            url:'http://187.188.96.133:8082/ServiceBosque/QR?',
                            type:'POST',
                            dataType:'json',
                            contentType:'application/json'
                    },
                    get:{
                            url:'http://187.188.96.133:8082/ServiceBosque/QR?',
                            type:'GET',
                            dataType:'json',
                            contentType:'application/json'
                    }
            },
            charge:{
                    upload:{
                            url:'http://187.188.96.133:8082/ServiceBosque/UploadShape?',
                            type:'GET',
                            dataType:'json',
                            contentType:'application/json'
                    },
                    download:{
                            url:'http://187.188.96.133:8082/ServiceBosque/DownloadCSV?',
                            type:'GET',
                            dataType:'json',
                            contentType:'application/json'
                    },
                    predio:{
                            url:'http://187.188.96.133:800/SIFEM/toolMaps/poligonos.html'
                    },
                    getSeed:{
                            url:'http://187.188.96.133:8082/ServiceBosque/CSV?',
                            type:'POST',
                            dataType:'json',
                            contentType:'application/x-www-form-urlencoded'
                    }
            },
            features:{
                    getPredios:{
                            url:'http://187.188.96.133:8082/ServiceBosque/Predios?',
                            type:'GET',
                            dataType:'json',
                            contentType:'application/json'
                    },
                    getLayers:{
                            url:'http://187.188.96.133:8082/ServiceBosque/Layers?',
                            type:'GET',
                            dataType:'json',
                            contentType:'application/json'
                    },
                    getRegions:{
                            url:'data/regiones.json',
                            type:'GET',
                            dataType:'json',
                            contentType:'application/json'
                    },
                    getInfoTheme:{
                            url:'http://187.188.96.133:8082/ServiceBosque/Totals?',
                            type:'GET',
                            dataType:'json',
                            contentType:'application/json'
                    },
                    getLayer:{
                            url:'http://187.188.96.133:8082/ServiceBosque/Predios?',
                            type:'GET',
                            dataType:'json',
                            contentType:'application/json'
                    },
                    deleteLayer:{
                            url:'http://187.188.96.133:8082/ServiceBosque/Layers?',
                            type:'POST',
                            dataType:'json',
                            contentType:'application/x-www-form-urlencoded'
                    }
            },
            identify:{
                    event:{
                            url:'http://187.188.96.133:8082/ServiceBosque/Predios?',
                            type:'GET',
                            dataType:'json',
                            contentType:'application/json'
                    }
            },
            search:{
                    event:{
                            //url:'http://187.188.96.133:8082/Service/Predios?',
                            url:'http://187.188.96.133:8082/ServiceBosque/Predios?',
                            type:'GET',
                            dataType:'json',
                            contentType:'application/json'
                    }
            },
            notification:{
                    event:{
                            url:'http://187.188.96.133:8082/Service/Actions?',
                            type:'GET',
                            dataType:'json',
                            contentType:'application/json'
                    }
            },
            graph:{
                    bottom:{
                            url:'http://187.188.96.133:8082/Service/Report?',
                            type:'GET',
                            dataType:'json',
                            contentType:'application/json'
                    }
            },
            progress:{
                 data:{
                        url:'data/progress.json',
                        type:'GET',
                        dataType:'json',
                        contentType:'application/json'
                }
                
            },
            tabulate:{
                    getFields:{
                            url:'http://187.188.96.133:8082/ServiceBosque/DataTable?',
                            type:'POST',
                            dataType:'json',
                            contentType: 'application/x-www-form-urlencoded'
                    },
                    getReport:{
                            url:'http://187.188.96.133:8082/ServiceBosque/DataTable?',
                            type:'POST',
                            dataType:'json',
                        contentType: 'application/x-www-form-urlencoded'
                    },
                    getGraph:{
                            url:'http://187.188.96.133:8082/ServiceBosque/Graph?',
                            type:'POST',
                            dataType:'json'
                    },
                    getSeed:{
                            url:'http://187.188.96.133:8082/ServiceBosque/CSV?',
                            type:'POST',
                            dataType:'json'
                    },
                    downloadCvs:{
                            url:'http://187.188.96.133:8082/ServiceBosque/DownloadCSV?',
                            type:'POST',
                            dataType:'json'
                    },
                    getSeedPdf:{
                            url:'http://187.188.96.133:8082/ServiceBosque/CSV?',
                            type:'POST',
                            dataType:'json'
                    },
                    downloadPdf:{
                            url:'http://187.188.96.133:8082/ServiceBosque/DownloadPDF?',
                            type:'POST',
                            dataType:'json'
                    }
            },
            executive:{
                    getFields:{
                            url:'http://187.188.96.133:8082/ServiceBosque/TablePredios?',
                            type:'POST',
                            dataType:'json'//,
                            //contentType: 'application/x-www-form-urlencoded'
                    },
                    getAniosAndPrograms:{
                            url:'http://187.188.96.133:8082/ServiceBosque/TablePrediosAnios?',
                            type:'POST',
                            dataType:'json'//,
                    },
                    getReport:{
                            url:'http://187.188.96.133:8082/ServiceBosque/ReportPredios?',
                            //url:'data/executive.txt',
			    type:'POST',
                            dataType:'json'//,
			    //contentType: 'application/x-www-form-urlencoded'
                    },
                    getGraph:{
                            url:'http://187.188.96.133:8082/ServiceBosque/Graph?',
                            type:'POST',
                            dataType:'json'
                    },
                    getSeed:{
                            url:'http://187.188.96.133:8082/ServiceBosque/CSV?',
                            type:'POST',
                            dataType:'json'
                    },
                    downloadCvs:{
                            url:'http://187.188.96.133:8082/ServiceBosque/DownloadCSV?',
                            type:'POST',
                            dataType:'json'
                    },
                    getSeedPdf:{
                            url:'http://187.188.96.133:8082/ServiceBosque/CSV?',
                            type:'POST',
                            dataType:'json'
                    },
                    downloadPdf:{
                            url:'http://187.188.96.133:8082/ServiceBosque/DownloadPDFReport?',
                            type:'POST',
                            dataType:'json'
                    }
            },
             UserLog:{
                keylog:{
                            url:'http://187.188.96.133:8082/ServiceBosque/Request_Log?',
                            type:'POST',
                            dataType:'json'
                        },
                keynombre:{
                            url:'http://187.188.96.133:8082/ServiceBosque/Request_Log?',
                            type:'POST',
                            dataType:'json'
                           }
            }
            
    }
    
});